/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.rcsas;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Arshad Khalid (TP058473)
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        AdminLoginHeading = new javax.swing.JLabel();
        CredentialHeading = new javax.swing.JLabel();
        AdminIDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        AdminIDTextfield = new javax.swing.JTextField();
        AdminLoginButton = new javax.swing.JButton();
        AdminBackButton = new javax.swing.JButton();
        AdminPasswordField = new javax.swing.JPasswordField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminLoginHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AdminLoginHeading.setForeground(new java.awt.Color(204, 0, 51));
        AdminLoginHeading.setText("ADMIN LOGIN");

        CredentialHeading.setFont(new java.awt.Font("Yu Gothic Light", 3, 18)); // NOI18N
        CredentialHeading.setText("Enter Credentials:");

        AdminIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminIDLabel.setText("ADMIN ID:");

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel.setText("Password:");

        AdminIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminIDTextfieldActionPerformed(evt);
            }
        });

        AdminLoginButton.setText("LOGIN");
        AdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginButtonActionPerformed(evt);
            }
        });

        AdminBackButton.setText("BACK");
        AdminBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBackButtonActionPerformed(evt);
            }
        });

        AdminPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AdminIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AdminIDTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CredentialHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PasswordLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AdminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminLoginHeading)))
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(AdminLoginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminBackButton)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdminLoginHeading)
                .addGap(42, 42, 42)
                .addComponent(CredentialHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminIDLabel)
                    .addComponent(AdminIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(AdminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminLoginButton)
                    .addComponent(AdminBackButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminIDTextfieldActionPerformed

    private void AdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginButtonActionPerformed
        // TODO add your handling code here:
        String AdminID= AdminIDTextfield.getText().trim();
        String AdminPassword= AdminPasswordField.getText().trim();
        
        //below are the username and password for the admin interface
        if (AdminID.equals("admin") && AdminPassword.equals("qwerty")) {
            AdminFeatures af= new AdminFeatures();
            af.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(AdminLoginButton, "Incorrect Username or password.\nPlease try again.");
            AdminIDTextfield.setText("");
            AdminPasswordField.setText("");
        }
    }//GEN-LAST:event_AdminLoginButtonActionPerformed

    private void AdminBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBackButtonActionPerformed
        // TODO add your handling code here:
        UserTypeLogin utl = new UserTypeLogin();
        utl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminBackButtonActionPerformed

    private void AdminPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPasswordFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AdminPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBackButton;
    private javax.swing.JLabel AdminIDLabel;
    private javax.swing.JTextField AdminIDTextfield;
    private javax.swing.JButton AdminLoginButton;
    private javax.swing.JLabel AdminLoginHeading;
    private javax.swing.JPasswordField AdminPasswordField;
    private javax.swing.JLabel CredentialHeading;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
