/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment.rcsas;

/**
 *
 * @author Arshad Khalid (TP058473)
 */
public class AdminFeatures extends javax.swing.JFrame {

    /**
     * Creates new form AdminFeatures
     */
    public AdminFeatures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminLabel = new javax.swing.JLabel();
        RCSASlabel = new javax.swing.JLabel();
        AddRecordsButton = new javax.swing.JButton();
        DisplayRecordsButton = new javax.swing.JButton();
        ModifyRecordButton = new javax.swing.JButton();
        SearchRecordButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        SortRecordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminLabel.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(102, 102, 255));
        AdminLabel.setText("Admin");

        RCSASlabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        RCSASlabel.setForeground(new java.awt.Color(255, 102, 0));
        RCSASlabel.setText("RCSAS");

        AddRecordsButton.setText("Add Records");
        AddRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRecordsButtonActionPerformed(evt);
            }
        });

        DisplayRecordsButton.setText("Display Records");
        DisplayRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRecordsButtonActionPerformed(evt);
            }
        });

        ModifyRecordButton.setText("Modify Records");
        ModifyRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyRecordButtonActionPerformed(evt);
            }
        });

        SearchRecordButton.setText("Search");
        SearchRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRecordButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("LOGOUT");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        SortRecordButton.setText("Sort Records");
        SortRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortRecordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddRecordsButton)
                            .addComponent(DisplayRecordsButton)
                            .addComponent(SortRecordButton))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModifyRecordButton)
                            .addComponent(SearchRecordButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(RCSASlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminLabel)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RCSASlabel)
                    .addComponent(AdminLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRecordsButton)
                    .addComponent(ModifyRecordButton))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayRecordsButton)
                    .addComponent(SearchRecordButton))
                .addGap(29, 29, 29)
                .addComponent(SortRecordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRecordsButtonActionPerformed
        // TODO add your handling code here:
        DisplayRecords dr= new DisplayRecords();
        dr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DisplayRecordsButtonActionPerformed

    private void AddRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRecordsButtonActionPerformed
        // TODO add your handling code here:
        AddRecords ar= new AddRecords();
        ar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddRecordsButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        Admin a= new Admin();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void ModifyRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyRecordButtonActionPerformed
        // TODO add your handling code here:
        ModifyRecords mr= new ModifyRecords();
        mr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ModifyRecordButtonActionPerformed

    private void SearchRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRecordButtonActionPerformed
        // TODO add your handling code here:
        SearchRecords sr= new SearchRecords();
        sr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SearchRecordButtonActionPerformed

    private void SortRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortRecordButtonActionPerformed
        // TODO add your handling code here:
        SortAndDisplay sad=new SortAndDisplay();
        sad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SortRecordButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFeatures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRecordsButton;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JButton DisplayRecordsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ModifyRecordButton;
    private javax.swing.JLabel RCSASlabel;
    private javax.swing.JButton SearchRecordButton;
    private javax.swing.JButton SortRecordButton;
    // End of variables declaration//GEN-END:variables
}
