/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
/**
 *
 * @author Chaixuen
 */
public class pfandstc extends javax.swing.JFrame {

    /**
     * Creates new form pfandstc
     */
    public pfandstc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rcsaslab = new javax.swing.JLabel();
        pfeedbackbut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pfeedbacktxt = new javax.swing.JEditorPane();
        stclab = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        vpplab = new javax.swing.JLabel();
        pplab = new javax.swing.JLabel();
        aplab = new javax.swing.JLabel();
        gplab = new javax.swing.JLabel();
        eplab = new javax.swing.JLabel();
        starlab = new javax.swing.JLabel();
        startxt = new javax.swing.JTextField();
        submitbut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        confirmbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sportID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        coachIDTextfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        SPORTtextfield = new javax.swing.JTextField();
        locationTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rcsaslab.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        rcsaslab.setForeground(new java.awt.Color(0, 204, 204));
        rcsaslab.setText("RCSAS");

        pfeedbackbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pfeedbackbut.setText("Provide Feedback");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        pfeedbacktxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(pfeedbacktxt);

        stclab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        stclab.setText("Star to Coach");

        slider.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        slider.setMajorTickSpacing(1);
        slider.setMaximum(5);
        slider.setMinimum(1);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setValue(1);

        vpplab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vpplab.setText("1 = Very Poor Performance");

        pplab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pplab.setText("2 = Poor Performance");

        aplab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        aplab.setText("3 = Average Performance");

        gplab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gplab.setText("4 = Good Performance");

        eplab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        eplab.setText("5 = Excellent Performance");

        starlab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        starlab.setText("Star:");

        startxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        submitbut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        submitbut.setForeground(new java.awt.Color(0, 204, 204));
        submitbut.setText("Submit");
        submitbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbutActionPerformed(evt);
            }
        });

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        backbut.setForeground(new java.awt.Color(255, 0, 0));
        backbut.setText("Back");
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        confirmbut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        confirmbut.setForeground(new java.awt.Color(0, 102, 255));
        confirmbut.setText("Confirm");
        confirmbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbutActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Sport ID:");

        jLabel2.setText("Coach ID:");

        coachIDTextfield.setEditable(false);

        jLabel3.setText("Location:");

        jLabel4.setText(" Specialized sport:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SPORTtextfield.setEditable(false);

        locationTextfield.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stclab)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pplab)
                                    .addComponent(vpplab)
                                    .addComponent(aplab)
                                    .addComponent(gplab)
                                    .addComponent(eplab)
                                    .addComponent(submitbut))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(coachIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(SPORTtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(locationTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sportID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                                                .addComponent(SearchButton)))))
                                                .addGap(8, 8, 8))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(backbut))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(rcsaslab))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(starlab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(confirmbut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pfeedbackbut)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rcsaslab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfeedbackbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stclab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vpplab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pplab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aplab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gplab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eplab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confirmbut)
                            .addComponent(starlab)
                            .addComponent(startxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitbut)
                            .addComponent(backbut)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(coachIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SPORTtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(locationTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        rsviewdetail vd = new rsviewdetail();
        vd.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    private void submitbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbutActionPerformed
        try
        {
            File f = new File("sportRecords.txt");
            String feedback = pfeedbacktxt.getText().trim();
            String star = startxt.getText().trim();
            String sportid= sportID.getText().trim();
            Scanner x=new Scanner(f);
                    
            try(PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter("Feedback_and_Star.txt",true))))
            {
                while (x.hasNext()) {                    
                    String line=x.nextLine();
                    if (line.contains(sportid)) {
                        
                        sportid=line;
                        String sport=x.nextLine();
                        String location= x.nextLine();
                        String coachid = x.nextLine();
                        
                        writer.println(coachid);
                        writer.println(sport);
                        writer.println(location);
                        writer.println(feedback);
                        writer.println(star);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error","Error message", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Error","Error message", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);
        tqsubmit tq = new tqsubmit();
        tq.setVisible(true);
    }//GEN-LAST:event_submitbutActionPerformed

    private void confirmbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbutActionPerformed
        startxt.setText(String.valueOf(slider.getValue()));
    }//GEN-LAST:event_confirmbutActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        try {
            File f = new File("sportRecords.txt");
            Scanner x=new Scanner(f);
            String sportid=sportID.getText().trim();
            
            while (x.hasNext()) {                    
                String line=x.nextLine();
                if (line.contains(sportid)) {
                    sportid=line;
                    String sport=x.nextLine();
                    String location= x.nextLine();
                    String coachid = x.nextLine();
                    
                    coachIDTextfield.setText(coachid);
                    SPORTtextfield.setText(sport);
                    locationTextfield.setText(location);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pfandstc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pfandstc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pfandstc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pfandstc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pfandstc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SPORTtextfield;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel aplab;
    private javax.swing.JButton backbut;
    private javax.swing.JTextField coachIDTextfield;
    private javax.swing.JButton confirmbut;
    private javax.swing.JLabel eplab;
    private javax.swing.JLabel gplab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField locationTextfield;
    private javax.swing.JLabel pfeedbackbut;
    private javax.swing.JEditorPane pfeedbacktxt;
    private javax.swing.JLabel pplab;
    private javax.swing.JLabel rcsaslab;
    private javax.swing.JSlider slider;
    private javax.swing.JTextField sportID;
    private javax.swing.JLabel starlab;
    private javax.swing.JTextField startxt;
    private javax.swing.JLabel stclab;
    private javax.swing.JButton submitbut;
    private javax.swing.JLabel vpplab;
    // End of variables declaration//GEN-END:variables
}
