/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaixuen
 */
public class rsloginGUI extends javax.swing.JFrame {

    /**
     * Creates new form rsloginGUI
     */
    public rsloginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginlab = new javax.swing.JLabel();
        snamelab = new javax.swing.JLabel();
        passlab = new javax.swing.JLabel();
        snametxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        logibut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        incorrecttxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(326, 351));

        loginlab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        loginlab.setText("Please Login");

        snamelab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        snamelab.setText("Student Name:");

        passlab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passlab.setText("Password:");

        snametxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        snametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snametxtActionPerformed(evt);
            }
        });

        logibut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        logibut.setForeground(new java.awt.Color(0, 204, 204));
        logibut.setText("Login");
        logibut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logibutActionPerformed(evt);
            }
        });

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backbut.setForeground(new java.awt.Color(255, 0, 0));
        backbut.setText("Back");
        backbut.setPreferredSize(new java.awt.Dimension(91, 25));
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        incorrecttxt.setEditable(false);
        incorrecttxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        incorrecttxt.setForeground(new java.awt.Color(255, 51, 51));
        incorrecttxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logibut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(snamelab)
                                    .addComponent(passlab))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(snametxt)
                                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(loginlab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(incorrecttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(loginlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incorrecttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snamelab)
                    .addComponent(snametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlab)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logibut)
                    .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logibutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logibutActionPerformed
    File file =new File("Registered_Student.txt");
    Scanner in = null;
    try 
    {
        in = new Scanner(file);
        while(in.hasNext())
        {
            String line=in.nextLine();
            String name=snametxt.getText();
            if(line.contains(name))
            {
                String pass=in.nextLine();
                if(passtxt.getText().equals(pass))
                {
                   this.setVisible(false);
                    rsviewdetail vd = new rsviewdetail();
                    vd.setVisible(true); 
                }
            }else
            {
                incorrecttxt.setText("Incorrect Name or Password");
            }
        }
    } 
    catch (Exception e) 
    {
        System.out.println("Error");
    }
    /*
    this.setVisible(false);
    rsviewdetail vd = new rsviewdetail();
    vd.setVisible(true);*/
    }//GEN-LAST:event_logibutActionPerformed

    private void snametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snametxtActionPerformed
        
    }//GEN-LAST:event_snametxtActionPerformed

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        smenu sm = new smenu();
        sm.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rsloginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rsloginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rsloginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rsloginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rsloginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut;
    private javax.swing.JTextField incorrecttxt;
    private javax.swing.JButton logibut;
    private javax.swing.JLabel loginlab;
    private javax.swing.JLabel passlab;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel snamelab;
    private javax.swing.JTextField snametxt;
    // End of variables declaration//GEN-END:variables
}
