/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;

/**
 *
 * @author Chaixuen
 */
public class rsvdetails extends javax.swing.JFrame {

    /**
     * Creates new form rsvdetails
     */
    public rsvdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rcsaslab = new javax.swing.JLabel();
        choicelab = new javax.swing.JLabel();
        docbut = new javax.swing.JButton();
        dosrbut = new javax.swing.JButton();
        borssbut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        logoutbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rcsaslab.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        rcsaslab.setForeground(new java.awt.Color(0, 204, 204));
        rcsaslab.setText("RCSAS");

        choicelab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        choicelab.setText("Please Select Your Choice:");

        docbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        docbut.setText("Detail of Coach");
        docbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docbutActionPerformed(evt);
            }
        });

        dosrbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dosrbut.setText("Detail of Self-Record");
        dosrbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosrbutActionPerformed(evt);
            }
        });

        borssbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        borssbut.setText("Detail of Registered Sport Schedule only");
        borssbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borssbutActionPerformed(evt);
            }
        });

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backbut.setForeground(new java.awt.Color(255, 0, 0));
        backbut.setText("Back");
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        logoutbut.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        logoutbut.setForeground(new java.awt.Color(255, 0, 0));
        logoutbut.setText("Logout");
        logoutbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choicelab)
                            .addComponent(borssbut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dosrbut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(docbut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rcsaslab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutbut))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rcsaslab))
                    .addComponent(logoutbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choicelab)
                .addGap(39, 39, 39)
                .addComponent(docbut)
                .addGap(18, 18, 18)
                .addComponent(dosrbut)
                .addGap(18, 18, 18)
                .addComponent(borssbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(backbut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        rsviewdetail sv = new rsviewdetail();
        sv.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    private void logoutbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbutActionPerformed
        this.setVisible(false);
        slogout sl = new slogout();
        sl.setVisible(true);
    }//GEN-LAST:event_logoutbutActionPerformed

    private void docbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docbutActionPerformed
        this.setVisible(false);
        vdcoach dc = new vdcoach();
        dc.setVisible(true);
    }//GEN-LAST:event_docbutActionPerformed

    private void dosrbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosrbutActionPerformed
        this.setVisible(false);
        vdselfrecord sr = new vdselfrecord();
        sr.setVisible(true);
    }//GEN-LAST:event_dosrbutActionPerformed

    private void borssbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borssbutActionPerformed
        this.setVisible(false);
        vdregistersports rs = new vdregistersports();
        rs.setVisible(true);
    }//GEN-LAST:event_borssbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rsvdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rsvdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rsvdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rsvdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rsvdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut;
    private javax.swing.JButton borssbut;
    private javax.swing.JLabel choicelab;
    private javax.swing.JButton docbut;
    private javax.swing.JButton dosrbut;
    private javax.swing.JButton logoutbut;
    private javax.swing.JLabel rcsaslab;
    // End of variables declaration//GEN-END:variables
}
