/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;

/**
 *
 * @author Chaixuen
 */
public class smenu extends javax.swing.JFrame {

    /**
     * Creates new form smenu
     */
    public smenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menurcsaslab = new javax.swing.JLabel();
        sportbut = new javax.swing.JButton();
        selectlab = new javax.swing.JLabel();
        schedulebut = new javax.swing.JButton();
        registerlab = new javax.swing.JLabel();
        registerbut = new javax.swing.JButton();
        loginbut = new javax.swing.JButton();
        loginlab = new javax.swing.JLabel();
        backbut = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menurcsaslab.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        menurcsaslab.setForeground(new java.awt.Color(0, 204, 204));
        menurcsaslab.setText("Welcome to RCSAS");

        sportbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sportbut.setText("View Detail of Sport");
        sportbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportbutActionPerformed(evt);
            }
        });

        selectlab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        selectlab.setText("Please Select Your Choice");

        schedulebut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        schedulebut.setText("View Detail of Sport Schedule");
        schedulebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedulebutActionPerformed(evt);
            }
        });

        registerlab.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        registerlab.setForeground(new java.awt.Color(255, 0, 0));
        registerlab.setText("Register to Access More Details");

        registerbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerbut.setText("Register");
        registerbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutActionPerformed(evt);
            }
        });

        loginbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loginbut.setText("Login");
        loginbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutActionPerformed(evt);
            }
        });

        loginlab.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        loginlab.setForeground(new java.awt.Color(0, 102, 255));
        loginlab.setText("Login if you have an Account");

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backbut.setForeground(new java.awt.Color(255, 0, 0));
        backbut.setText("Back");
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(schedulebut, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(menurcsaslab)
                                    .addComponent(sportbut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectlab))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(registerbut, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registerlab)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menurcsaslab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectlab)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbut)
                    .addComponent(loginbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerlab)
                    .addComponent(loginlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sportbut)
                        .addGap(18, 18, 18)
                        .addComponent(schedulebut)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backbut)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbutActionPerformed
        this.setVisible(false);
        rsloginGUI rl = new rsloginGUI();
        rl.setVisible(true);
    }//GEN-LAST:event_loginbutActionPerformed

    private void registerbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutActionPerformed
        this.setVisible(false);
        sregister sr = new sregister();
        sr.setVisible(true);
    }//GEN-LAST:event_registerbutActionPerformed

    private void sportbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportbutActionPerformed
        this.setVisible(false);
        vdetailsport ds = new vdetailsport();
        ds.setVisible(true);
    }//GEN-LAST:event_sportbutActionPerformed

    private void schedulebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedulebutActionPerformed
        this.setVisible(false);
        vdschedulesp ss = new vdschedulesp();
        ss.setVisible(true);
    }//GEN-LAST:event_schedulebutActionPerformed

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        assignment.rcsas.UserTypeLogin menu=new assignment.rcsas.UserTypeLogin();
        menu.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(smenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(smenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(smenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(smenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbut;
    private javax.swing.JLabel loginlab;
    private javax.swing.JLabel menurcsaslab;
    private javax.swing.JButton registerbut;
    private javax.swing.JLabel registerlab;
    private javax.swing.JButton schedulebut;
    private javax.swing.JLabel selectlab;
    private javax.swing.JButton sportbut;
    // End of variables declaration//GEN-END:variables
}
