/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;
import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Random;

/**
 *
 * @author Chaixuen
 */
public class sregister extends javax.swing.JFrame 
{

    /**
     * Creates new form sregister
     */
    public sregister() {
        initComponents();
    }
    class studentFile {

    studentFile(File f) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void write(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        rformlab = new javax.swing.JLabel();
        insertlab = new javax.swing.JLabel();
        namelab = new javax.swing.JLabel();
        agelab = new javax.swing.JLabel();
        iclab = new javax.swing.JLabel();
        doblab = new javax.swing.JLabel();
        emaillab = new javax.swing.JLabel();
        addlab = new javax.swing.JLabel();
        genderlab = new javax.swing.JLabel();
        contactlab = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        gendertxt = new javax.swing.JTextField();
        ictxt = new javax.swing.JTextField();
        dobtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        contacttxt = new javax.swing.JTextField();
        selectsportlab = new javax.swing.JLabel();
        paymentlab = new javax.swing.JLabel();
        paymenttxt = new javax.swing.JTextField();
        passlab = new javax.swing.JLabel();
        passtxt = new javax.swing.JPasswordField();
        registerbut = new javax.swing.JButton();
        backbut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addtxt = new javax.swing.JEditorPane();
        sportcombo = new javax.swing.JComboBox<>();
        confirmbut = new javax.swing.JButton();
        sportlab = new javax.swing.JLabel();
        sporttxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IDfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rformlab.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        rformlab.setForeground(new java.awt.Color(0, 204, 204));
        rformlab.setText("RCSAS Registeration Form");

        insertlab.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        insertlab.setText("Please insert your Details");

        namelab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        namelab.setText("Name:");

        agelab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        agelab.setText("Age:");

        iclab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        iclab.setText("I.C NO. :");

        doblab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        doblab.setText("Date of Birth(dd/mm/yyyy):");

        emaillab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        emaillab.setText("Email:");

        addlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        addlab.setText("Address:");

        genderlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        genderlab.setText("Gender(F/M):");

        contactlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        contactlab.setText("Contact NO. :");

        nametxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        agetxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        gendertxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gendertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendertxtActionPerformed(evt);
            }
        });

        ictxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        dobtxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        emailtxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        contacttxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        selectsportlab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        selectsportlab.setText("Select a Sport");

        paymentlab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        paymentlab.setText("Payment (RM):");

        paymenttxt.setEditable(false);
        paymenttxt.setBackground(new java.awt.Color(255, 255, 255));
        paymenttxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        paymenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttxtActionPerformed(evt);
            }
        });

        passlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        passlab.setText("Password:");

        passtxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        registerbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registerbut.setForeground(new java.awt.Color(0, 204, 204));
        registerbut.setText("Register");
        registerbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbutActionPerformed(evt);
            }
        });

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backbut.setForeground(new java.awt.Color(250, 0, 0));
        backbut.setText("Back");
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        addtxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(addtxt);

        sportcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sportcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Volleyball", "Table Tennis", "Basketball", "Achery", "Tennis", "Criket", "Gymnastics", "Football" }));

        confirmbut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        confirmbut.setForeground(new java.awt.Color(0, 102, 255));
        confirmbut.setText("Confirm sport");
        confirmbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbutActionPerformed(evt);
            }
        });

        sportlab.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sportlab.setText("Sport:");

        sporttxt.setEditable(false);
        sporttxt.setBackground(new java.awt.Color(255, 255, 255));
        sporttxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sporttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sporttxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Auto ID:");

        IDfield.setEditable(false);
        IDfield.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(confirmbut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymentlab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paymenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sportcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sportlab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rformlab)
                                        .addComponent(insertlab)
                                        .addComponent(addlab)
                                        .addComponent(passlab)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(71, 71, 71)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(doblab)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(94, 94, 94))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(namelab)
                                                .addComponent(genderlab)
                                                .addComponent(emaillab))
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(gendertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(iclab)
                                                .addComponent(contactlab)
                                                .addComponent(agelab))
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(contacttxt)
                                                .addComponent(ictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(selectsportlab)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerbut, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addGap(260, 260, 260)
                                .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rformlab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertlab)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namelab)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gendertxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderlab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emaillab)
                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agelab)
                            .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iclab)
                            .addComponent(ictxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactlab)
                            .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblab)
                    .addComponent(dobtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addlab)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passlab)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectsportlab)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportlab)
                    .addComponent(sporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentlab)
                    .addComponent(paymenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerbut)
                    .addComponent(backbut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        smenu sm = new smenu();
        sm.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    private void registerbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbutActionPerformed
        if(nametxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(agetxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(gendertxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(ictxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(emailtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(contacttxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(dobtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(addtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(sporttxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(paymenttxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please finish the form.","Error Message",JOptionPane.ERROR_MESSAGE);
        }
        else if(passtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter password.","Error Message",JOptionPane.ERROR_MESSAGE);
        }else
        {
            try
            {
                File f = new File("Registered_Student.txt");
                String name = nametxt.getText().trim();
                String age = agetxt.getText().trim();
                String gender = gendertxt.getText().trim();
                String ic = ictxt.getText().trim();
                String email = emailtxt.getText().trim();
                String dob = dobtxt.getText().trim();
                String contact = contacttxt.getText().trim();
                String address = addtxt.getText().trim();
                String password = passtxt.getText().trim();
                String sport = sporttxt.getText().trim();
                String payment = paymenttxt.getText().trim();
                
                //creating random ID
                String upperAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                String lowerAlphabet = "abcdefghijklmnopqrstuvwxyz";
                String numbers = "0123456789";
            
                //joining all the letters and numbers to creata an alphanumeric string
                String alphaNumeric = upperAlphabet + lowerAlphabet + numbers;
            
                //we creata object for stringbuilder and random
                StringBuilder sb = new StringBuilder();
                Random random = new Random();
            
                int length = 4; //length of ID we want

                for(int i = 0; i < length; i++) {
                    // generate random index number
                    int index = random.nextInt(alphaNumeric.length());
                    
                    // get character specified by index
                    // from the string
                    char randomChar = alphaNumeric.charAt(index);

                    // append the character to string builder
                    sb.append(randomChar);
                }
                String studentID = sb.toString();
                IDfield.setText(studentID);
                    
                try(PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter("Registered_Student.txt",true))))
                {
                    writer.println(studentID);
                    writer.println(name);
                    writer.println(password);
                    writer.println(age);
                    writer.println(gender);
                    writer.println(ic);
                    writer.println(email);
                    writer.println(dob);
                    writer.println(contact);
                    writer.println(address);
                    writer.println(sport);
                    writer.println(payment);
                }
                catch(Exception e)
                {
                    System.out.println("Error");
                }
            }
            catch(Exception e)
            {
                System.out.println("Error");
            }
                this.setVisible(false);
                rsloginGUI rl = new rsloginGUI();
                rl.setVisible(true);
        }
    }//GEN-LAST:event_registerbutActionPerformed

    private void gendertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendertxtActionPerformed

    private void confirmbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbutActionPerformed
        sporttxt.setText(sportcombo.getSelectedItem().toString());
        int swimming=100,
                badminton=100,
                volleyball=100, 
                tabletennis=200, 
                basketball=250, 
                achery=300, 
                tennis=250,
                criket=300, 
                gymnastics=450,
                football=400;
        if(sportcombo.getSelectedItem().equals("Swimming"))
        {
            paymenttxt.setText(""+swimming);
        }
        else if(sportcombo.getSelectedItem().equals("Badminton"))
        {
            paymenttxt.setText(""+badminton);
        }
        else if(sportcombo.getSelectedItem().equals("Volleyball"))
        {
            paymenttxt.setText(""+volleyball);
        }
        else if(sportcombo.getSelectedItem().equals("Table Tennis"))
        {
            paymenttxt.setText(""+tabletennis);
        }
        else if(sportcombo.getSelectedItem().equals("Basketball"))
        {
            paymenttxt.setText(""+basketball);
        }
        else if(sportcombo.getSelectedItem().equals("Achery"))
        {
            paymenttxt.setText(""+achery);
        }
        else if(sportcombo.getSelectedItem().equals("Tennis"))
        {
            paymenttxt.setText(""+tennis);
        }
        else if(sportcombo.getSelectedItem().equals("Criket"))
        {
            paymenttxt.setText(""+criket);
        }
        else if(sportcombo.getSelectedItem().equals("Gymnastics"))
        {
            paymenttxt.setText(""+gymnastics);
        }
        else if(sportcombo.getSelectedItem().equals("Football"))
        {
            paymenttxt.setText(""+football);
        }
    }//GEN-LAST:event_confirmbutActionPerformed

    private void paymenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttxtActionPerformed

    }//GEN-LAST:event_paymenttxtActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void sporttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sporttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sporttxtActionPerformed

    private void IDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDfield;
    private javax.swing.JLabel addlab;
    private javax.swing.JEditorPane addtxt;
    private javax.swing.JLabel agelab;
    private javax.swing.JTextField agetxt;
    private javax.swing.JButton backbut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton confirmbut;
    private javax.swing.JLabel contactlab;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JLabel doblab;
    private javax.swing.JTextField dobtxt;
    private javax.swing.JLabel emaillab;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel genderlab;
    private javax.swing.JTextField gendertxt;
    private javax.swing.JLabel iclab;
    private javax.swing.JTextField ictxt;
    private javax.swing.JLabel insertlab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel namelab;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel passlab;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JLabel paymentlab;
    private javax.swing.JTextField paymenttxt;
    private javax.swing.JButton registerbut;
    private javax.swing.JLabel rformlab;
    private javax.swing.JLabel selectsportlab;
    private javax.swing.JComboBox<String> sportcombo;
    private javax.swing.JLabel sportlab;
    private javax.swing.JTextField sporttxt;
    // End of variables declaration//GEN-END:variables
}
