/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rslogin;

import java.io.File;
import java.util.Scanner;

/**
 *
 * @author Chaixuen
 */
public class vdregistersports extends javax.swing.JFrame {

    /**
     * Creates new form vdregistersports
     */
    public vdregistersports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rcsaslab = new javax.swing.JLabel();
        dorsslab = new javax.swing.JLabel();
        backbut = new javax.swing.JButton();
        sportcombo = new javax.swing.JComboBox<>();
        sportlab = new javax.swing.JLabel();
        sporttxt = new javax.swing.JTextField();
        confirmbut = new javax.swing.JButton();
        viewbut = new javax.swing.JButton();
        clearbut = new javax.swing.JButton();
        schedulelab = new javax.swing.JLabel();
        sportlab1 = new javax.swing.JLabel();
        locationlab = new javax.swing.JLabel();
        locationtxt = new javax.swing.JTextField();
        timelab = new javax.swing.JLabel();
        timetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rcsaslab.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        rcsaslab.setForeground(new java.awt.Color(0, 204, 204));
        rcsaslab.setText("RCSAS");

        dorsslab.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dorsslab.setText("Details of Registered Sport Schedule");

        backbut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backbut.setForeground(new java.awt.Color(255, 0, 0));
        backbut.setText("Back");
        backbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutActionPerformed(evt);
            }
        });

        sportcombo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sportcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Swimming", "Badminton", "Volleyball", "Table Tennis", "Basketball", "Achery", "Tennis", "Criket", "Gymnastics", "Football" }));

        sportlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sportlab.setText("Sport:");

        sporttxt.setEditable(false);
        sporttxt.setBackground(new java.awt.Color(255, 255, 255));
        sporttxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sporttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sporttxtActionPerformed(evt);
            }
        });

        confirmbut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        confirmbut.setForeground(new java.awt.Color(0, 102, 255));
        confirmbut.setText("Confirm sport");
        confirmbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbutActionPerformed(evt);
            }
        });

        viewbut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        viewbut.setForeground(new java.awt.Color(0, 102, 255));
        viewbut.setText("View");
        viewbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbutActionPerformed(evt);
            }
        });

        clearbut.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        clearbut.setForeground(new java.awt.Color(255, 102, 51));
        clearbut.setText("Clear");
        clearbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutActionPerformed(evt);
            }
        });

        schedulelab.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        schedulelab.setText("Sport Schedules:");

        sportlab1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sportlab1.setText("Please select the sport that you registered:");

        locationlab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        locationlab.setText("Location:");

        locationtxt.setEditable(false);
        locationtxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        locationtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationtxtActionPerformed(evt);
            }
        });

        timelab.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        timelab.setText("Time:");

        timetxt.setEditable(false);
        timetxt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sportlab1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                                .addComponent(backbut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(locationlab)
                                            .addComponent(timelab))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(locationtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                            .addComponent(timetxt))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(viewbut)
                                            .addComponent(clearbut)))
                                    .addComponent(dorsslab)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sportcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(sportlab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rcsaslab)
                                    .addComponent(schedulelab)
                                    .addComponent(confirmbut))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rcsaslab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dorsslab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sportlab1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sportcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sporttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportlab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmbut)
                .addGap(8, 8, 8)
                .addComponent(schedulelab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewbut)
                            .addComponent(locationlab)
                            .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearbut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(timetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timelab)))
                        .addGap(45, 59, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backbut)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutActionPerformed
        this.setVisible(false);
        rsvdetails vd = new rsvdetails();
        vd.setVisible(true);
    }//GEN-LAST:event_backbutActionPerformed

    private void sporttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sporttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sporttxtActionPerformed

    private void confirmbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbutActionPerformed
        sporttxt.setText(sportcombo.getSelectedItem().toString());
    }//GEN-LAST:event_confirmbutActionPerformed

    private void viewbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbutActionPerformed
        File file =new File("schedule.txt");
        Scanner in = null;
        try 
        {
            in = new Scanner(file);
            while(in.hasNext())
            {
                String line=in.nextLine();
                String name=sporttxt.getText();
                if(line.contains(name))
                {
                    String location=in.nextLine();
                    String code = in.nextLine();
                    String time=in.nextLine();
                    locationtxt.setText(location);
                    timetxt.setText(time);
                }
            }
        }
        catch (Exception e) 
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_viewbutActionPerformed

    private void clearbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutActionPerformed
        sporttxt.setText("");
        locationtxt.setText("");
        timetxt.setText("");
    }//GEN-LAST:event_clearbutActionPerformed

    private void locationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vdregistersports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vdregistersports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vdregistersports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vdregistersports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vdregistersports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbut;
    private javax.swing.JButton clearbut;
    private javax.swing.JButton confirmbut;
    private javax.swing.JLabel dorsslab;
    private javax.swing.JLabel locationlab;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JLabel rcsaslab;
    private javax.swing.JLabel schedulelab;
    private javax.swing.JComboBox<String> sportcombo;
    private javax.swing.JLabel sportlab;
    private javax.swing.JLabel sportlab1;
    private javax.swing.JTextField sporttxt;
    private javax.swing.JLabel timelab;
    private javax.swing.JTextField timetxt;
    private javax.swing.JButton viewbut;
    // End of variables declaration//GEN-END:variables
}
